config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
  	get "signin" => 'devise/sessions#new'
  	delete "signout" => 'devise/sessions#destroy'
  	get "signup" => 'devise/registrations#new'
  end
  root 'pages#home'

  get 'about' => 'pages#about'

  get 'contact' => 'pages#contact'

  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter

	def authorized?(action, subject = nil)
		user && user.admin?
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def access_denied(exception)
  	redirect_to root_path, alert: exception.message
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostBuddy Pet Finder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-toggleable-sm navbar-inverse bg-inverse">
      <div class="container">
        <%= link_to "LostBuddy Pet Finder", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link" %></li>
        </ul>

        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Log out", signout_path, method: :delete, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Sign in", signin_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Sign up", signup_path, class: "btn btn-success" %></li> 
          <% end %>
        </ul>
      </div>
    </nav>


    <!-- Flaash Messages -->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2017 Lostbuddy Pet Finder www.lostbuddy.pet</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<!-- <h1>About Us</h1>
<p>After losing several pets and spending hours on multiple sites, we decided to try and find a better way.  With Lost Buddy, your lost pet's information is used by machine learning algorithms to search all other pet finding sites, shelters and ads to better help you locate your animal.</p>
<p>Additionally, your pet's information is shared by thousands in your geographical area thereby increasing the chances your lost buddy--your beloved pet will be found.</p> -->

<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>After losing several pets and spending hours on multiple sites, we decided to try and find a better way.  With Lost Buddy, your lost pet's information is used by machine learning algorithms to search all other pet finding sites, shelters and ads to better help you locate your animal.</p>

		<p>Additionally, your pet's information is shared by thousands in your geographical area thereby increasing the chances your lost buddy--your beloved pet--will be found</p>
    </div>
</div>

app/views/pages/contact-us.erb
<h1>Contact Us</h1>
<p>christopher.davies02@gmail.com</p>

app/views/pages/contact.html.erb
<!-- <h1>You can contact us at</h1>
<p>PetLover@lostbuddy.pet</p> -->

<div class="jumbotron">
    <div class="container">
        <h1>Contact us</h1>
        <p>PetLover@lostbuddy.pet <a href="http://lostbuddy.pet">Lost Buddy Pet Finder</a>.</p>
    </div>
</div>

app/views/pages/home.html.erb
<!-- <h1>Welcome to lostbuddy.pet the best place to locate your lost buddy</h1>
<p>Getting started is easy, just click the sign-in button below where you'll be prompted to enter some basic information and get started finding your lost pet.</p>
<p>Pet Finder Sign-in</p> -->

<% if user_signed_in? %>

    <div class="jumbotron jumbotron-home">
        <div class="container">
            <h1>Welcome Back to LostBuddy!</h1> 
        </div>
    </div> 

 <% else %>    

    <div class="jumbotron jumbotron-home">
        <div class="container">
            <h1>Welcome to LostBuddy</h1>
            <p>Where finding your lost pet is simplified.</p>
            <%= link_to "Learn more »", "#", class: "btn btn-success btn-lg" %> 
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h2>Simple</h2>
                <p>We harness the power of the internet to help you find your lost animal. We search everywhere, so you don't have to.</p>
                <p><%= link_to "View details", "#", class: "btn btn-success" %></p>
            </div>
            <div class="col-md-4">
                <h2>Fast</h2>
                <p>Our search algorithms will instantly match your pet's details with databases in your area.  You can be notified of results via text and/or email.</p>
                <p><%= link_to "View details", "#", class: "btn btn-success" %></p>
            </div>
            <div class="col-md-4">
                <h2>Dependable</h2>
                <p>Search results are automatically matched with your pet's information, increasing your chance of a match and successful retrieval.</p>
                <p><%= link_to "View details", "#", class: "btn btn-success" %></p>
            </div>
        </div>
    </div>
    
<% end %>